import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.crux.examples.counter.routing"

    compileSdk {
        version = release(36)
    }

    defaultConfig {
        minSdk = 34
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlin {
        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
    }

    sourceSets {
        getByName("main") {
            // types are generated by the codegen binary; jniLibs are built by boltffi pack android
            kotlin.srcDirs("${projectDir}/../generated")
            jniLibs.srcDirs("${projectDir}/../generated/jniLibs")
        }
    }
}

dependencies {
    // The generated `Core` runs each request on a `CoroutineScope` and
    // publishes the view model as a `StateFlow`, so both appear in this
    // module's API. The typegen's own `build.gradle.kts` declares this, but
    // these sources come in through `srcDirs` instead, so the module has to.
    api(libs.kotlinx.coroutines.core)
}
