[package]
name = "shared"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[features]
default = ["std"]
# On by default. Turn it off to build the core for an embedded target.
std = [
    "chrono/std",
    "crux_core/std",
    "crux_http/std",
    "crux_http/encoding",
    "facet/std",
    "futures/std",
    "serde/std",
    "serde_json/std",
    "url/std",
]
# ANCHOR: facet_typegen
facet_typegen = [
    "crux_core/facet_typegen",
    "crux_http/facet_typegen",
]
# ANCHOR_END: facet_typegen

[dependencies]
chrono.workspace = true
crux_core.workspace = true
crux_http.workspace = true
facet.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
url.workspace = true

[lints]
workspace = true

[dev-dependencies]
insta = { version = "1.48.0", features = ["yaml"] }
crux_core = { workspace = true, features = ["testing"] }

# wasm
[target.'cfg(target_family = "wasm")'.dependencies]
getrandom = { version = "=0.3.4", features = ["wasm_js"] }
