name: SimpleCounter
packages:
  Shared:
    path: ./generated/Shared
  App:
    path: ./generated/App
options:
  bundleIdPrefix: com.crux.examples.simplecounter.macos
attributes:
  BuildIndependentTargetsInParallel: true
targets:
  SimpleCounter:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    sources: [SimpleCounter]
    dependencies:
      - package: Shared
      - package: App
    info:
      path: SimpleCounter/Info.plist
      properties:
        NSSupportsAutomaticGraphicsSwitching: true
    settings:
      OTHER_LDFLAGS: [-w]
      ENABLE_USER_SCRIPT_SANDBOXING: NO
