name: CatFacts
packages:
  Shared:
    path: ./generated/Shared
  App:
    path: ./generated/App
options:
  bundleIdPrefix: com.example.bridge-perf
attributes:
  BuildIndependentTargetsInParallel: true
targets:
  CatFacts:
    type: application
    platform: iOS
    deploymentTarget: 18.0
    sources: [CatFacts]
    dependencies:
      - package: Shared
      - package: App
    info:
      path: CatFacts/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
