[package]
name = "shared_types"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]

[build-dependencies]
anyhow.workspace = true
crux_core = { workspace = true, features = ["facet_typegen"] }
crux_http = { workspace = true, features = ["facet_typegen"] }
serde.workspace = true
serde_json = "1.0.140"
shared = { features = ["facet_typegen"], path = "../shared" }
