mod lib '../../lib.just'

default: dev

common := "shared web-leptos web-nextjs Android"
shells := if os() == "macos" { common + " apple" } else { common }

# checks required tools across all shells
[script('sh')]
doctor:
    for shell in {{ shells }}; do
        echo '{{ style("command") }}'"$shell"':{{ NORMAL }}'
        just "$shell/doctor"
        echo ''
    done

# local development workflow
[script('sh')]
dev:
    for shell in {{ shells }}; do
        echo '{{ style("command") }}'"$shell"'/dev:{{ NORMAL }}'
        just "$shell/dev"
    done

# CI workflow
[script('sh')]
ci:
    for shell in {{ shells }}; do
        echo '{{ style("command") }}'"$shell"'/ci:{{ NORMAL }}'
        just "$shell/ci"
    done
