mod lib '../lib.just'

default: dev

shells := "shared tui web-leptos web-yew web-dioxus web-nextjs web-react-router tauri apple Android"

# checks required tools across all shells
doctor:
    #!/usr/bin/env bash
    for shell in {{ shells }}; do
        echo '{{ style("command") }}'"$shell"':{{ NORMAL }}'
        just "$shell/doctor"
        echo ''
    done

# local development workflow
dev:
    #!/usr/bin/env bash
    for shell in {{ shells }}; do
        echo '{{ style("command") }}'"$shell"'/dev:{{ NORMAL }}'
        just "$shell/dev"
    done

# CI workflow
ci:
    #!/usr/bin/env bash
    for shell in {{ shells }}; do
        echo '{{ style("command") }}'"$shell"'/ci:{{ NORMAL }}'
        just "$shell/ci"
    done
