name: Notes
packages:
  Shared:
    path: ./generated/Shared
  App:
    path: ./generated/App
options:
  bundleIdPrefix: com.crux.example.counter
targets:
  Notes:
    type: application
    platform: iOS
    deploymentTarget: 18.0
    sources: [Notes]
    dependencies:
      - package: Shared
      - package: App
    info:
      path: Notes/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
