name: Weather
packages:
  Shared:
    path: ./generated/Shared
  App:
    path: ./generated/App
options:
  bundleIdPrefix: com.crux.example
attributes:
  BuildIndependentTargetsInParallel: true
targets:
  Weather:
    type: application
    platform: iOS
    deploymentTarget: 18.0
    sources: [Weather]
    dependencies:
      - package: Shared
      - package: App
    info:
      path: Weather/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
        NSLocationWhenInUseUsageDescription: "This app needs access to your location to provide weather information."
