// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CruxCore>>
abstract class CruxCore implements RustOpaqueInterface {
  factory CruxCore() => RustLib.instance.api.crateApiCoreCruxCoreNew();

  Future<Uint8List> resolve({required int id, required List<int> data});

  Future<Uint8List> update({required List<int> data});

  Future<Uint8List> view();
}
