build:
    just Android/build
    just cli/build
    just iOS/build
    just web-nextjs/build
    just web-yew/build

clean:
    just Android/clean
    just cli/clean
    just iOS/clean
    just web-nextjs/clean
    just web-yew/clean

test:
    cargo nextest run
