# ANCHOR: manifest
[package]
name = "shared"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[lints.clippy]
pedantic = "warn"
nursery = "warn"

# ANCHOR: typegen_deps
[dependencies]
facet.workspace = true
# ANCHOR_END: typegen_deps
crux_core.workspace = true
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
crux_core = { workspace = true, features = ["testing"] }

# ANCHOR: typegen
[features]
facet_typegen = ["crux_core/facet_typegen"]
# ANCHOR_END: typegen
# ANCHOR_END: manifest
# On by default. Turn it off to build the core for an embedded target.
std = ["crux_core/std", "facet/std", "serde/std"]
default = ["std"]
