package counter-next:shared;

world shared {
    export update: func(data: list<u8>) -> result<list<u8>, string>;
    export resolve: func(effect-id: u32, data: list<u8>) -> result<list<u8>, string>;
    export view: func() -> result<list<u8>, string>;
    export schema: func() -> string;
}
