name: BridgePerf
packages:
  Shared:
    path: ../shared/generated/swift/Shared
  App:
    path: ../shared/generated/swift/App
options:
  bundleIdPrefix: com.example.bridge-perf
attributes:
  BuildIndependentTargetsInParallel: true
targets:
  BridgePerf:
    type: application
    platform: iOS
    deploymentTarget: 18.0
    sources: [BridgePerf]
    dependencies:
      - package: Shared
      - package: App
    info:
      path: BridgePerf/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
