mod lib '../../lib.just'

default: dev

# --------------------------------------------------------------------------
# Development
# --------------------------------------------------------------------------

# checks required tools are installed
doctor:
    @echo '{{ style("command") }}doctor:{{ NORMAL }}'
    @just lib::check-shared

# auto-fix formatting issues
fix:
    @echo '{{ style("command") }}fix:{{ NORMAL }}'
    cargo fmt

# validate formatting and lint
check:
    @echo '{{ style("command") }}check:{{ NORMAL }}'
    cargo fmt -- --check
    cargo clippy -p shared -- -D warnings
    cargo clippy -p shared --target wasm32-unknown-unknown --features wasm_bindgen -- -D warnings

# build the shared library
build:
    @echo '{{ style("command") }}build:{{ NORMAL }}'
    cargo build -p shared

# run tests
test:
    @echo '{{ style("command") }}test:{{ NORMAL }}'
    cargo nextest run -p shared

# clean build artifacts
clean:
    @echo '{{ style("command") }}clean:{{ NORMAL }}'
    cargo clean

# local development workflow
dev: fix check build test

# CI workflow
ci: check build test
