mod lib '../lib.just'

default: dev

examples := "counter counter-http counter-middleware notes weather"

# checks required tools across all examples
[script('bash')]
doctor:
    for example in {{ examples }}; do
        echo '{{ style("command") }}'"$example"':{{ NORMAL }}'
        just "$example/doctor"
        echo ''
    done

# local development workflow
[script('bash')]
dev:
    set -euo pipefail
    for example in {{ examples }}; do
        echo '{{ style("command") }}'"$example"'/dev:{{ NORMAL }}'
        just "$example/dev"
    done

# clean build artefacts in all examples
[script('bash')]
clean:
    set -euo pipefail
    for example in {{ examples }}; do
        echo '{{ style("command") }}'"$example"'/clean:{{ NORMAL }}'
        just "$example/clean"
    done

# fix formatting in all examples
[script('bash')]
fix:
    set -euo pipefail
    for example in {{ examples }}; do
        echo '{{ style("command") }}'"$example"'/fix:{{ NORMAL }}'
        just "$example/fix"
    done

# CI workflow
[script('bash')]
ci:
    set -euo pipefail
    for example in {{ examples }}; do
        echo '{{ style("command") }}'"$example"'/ci:{{ NORMAL }}'
        just "$example/ci"
    done
