mod lib '../lib.just'

default: dev

examples := "counter counter-http counter-middleware notes weather"

# checks required tools across all examples
[script('sh')]
doctor:
    for example in {{ examples }}; do
        echo '{{ style("command") }}'"$example"':{{ NORMAL }}'
        just "$example/doctor"
        echo ''
    done

# local development workflow
[script('sh')]
dev:
    for example in {{ examples }}; do
        echo '{{ style("command") }}'"$example"'/dev:{{ NORMAL }}'
        just "$example/dev"
    done

# CI workflow
[script('sh')]
ci:
    for example in {{ examples }}; do
        echo '{{ style("command") }}'"$example"'/ci:{{ NORMAL }}'
        just "$example/ci"
    done
