name: TapToPay
packages:
  Shared:
    path: ./generated/Shared
  App:
    path: ./generated/App
options:
  bundleIdPrefix: com.crux.example.tap-to-pay
attributes:
  BuildIndependentTargetsInParallel: true
targets:
  TapToPay:
    type: application
    platform: iOS
    deploymentTarget: 18.0
    sources: [TapToPay]
    dependencies:
      - package: Shared
      - package: App
    info:
      path: TapToPay/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
