# Enums with tuple variants, and their associated information.
query {
  Crate {
    item {
      ... on ImplOwner {
        # name @output
        visibility_limit @filter(op: "=", value: ["$public"])

        importable_path {
          path @output
        }

        # name @filter(op: "=", value: ["$app"]) @output
      }
    }
  }
}
