# Enums with tuple variants, and their associated information.
query {
  Crate {
    item {
      ... on Enum {
        enum_name: name @output

        # set "variant_" prefix for outputs within
        variant_: variant {
          # discard all non-tuple enum variants
          ... on TupleVariant {
            name @output
            docs @output

            # override output prefixes by explicitly naming outputs
            attrs @output(name: "attributes")
          }
        }
      }
    }
  }
}
