name: CounterApp
packages:
  Shared:
    path: ../shared/Shared
  SharedTypes:
    path: ../shared_types/generated/swift/SharedTypes
options:
  bundleIdPrefix: com.crux.example.counter
targets:
  CounterApp:
    type: application
    platform: iOS
    deploymentTarget: 18.0
    sources: [CounterApp]
    dependencies:
      - package: Shared
      - package: SharedTypes
    info:
      path: CounterApp/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchScreen: {}
